[VL] 08 Attributierte Grammatiken
Compilerbau/CB-Lecture-Bachelor pull request #11
Opened 2022-06-08 17:38 UTC by malt-r

Also added placeholder for "Symboltabellen mit ANTLR"

2022-06-08 18:39 UTC, cagix requested changes
@malt-r Sieht gut aus. Die Änderungen zu `attribgrammars.md` sollte @bcg7 approven.

Zum neuen `antlr.md`: Könntest Du da bitte auch den Rest vom Template mit reinkopieren (`.hugo/hugo-lecture/archetypes/lecture-cg/index.md`) - der Titel passt schon, aber der Rest wäre auch noch gut, wenn es von Anfang an drin ist ... :)

2022-06-08 19:54 UTC, bcg7 commented
Hier  habe ich hoch Fragen für morgen.

2022-06-08 19:59 UTC, bcg7 commented
Hat sich erledigt, ich hatte nicht richtig gelesen.

2022-06-09 07:23 UTC, bcg7 approved these changes

2022-07-20 10:37 UTC, cagix requested changes
lgtm ... sollte aber durch @bcg7 freigegeben werden

@malt-r der teil mit `symboltables/antlr.md` gehört hier aber nicht rein, oder? kannst du das bitte hier rauslösen und einen neuen pull-request dafür aufmachen?

2022-07-21 06:34 UTC, malt-r commented
> lgtm ... sollte aber durch @bcg7 freigegeben werden
> 
> @malt-r der teil mit `symboltables/antlr.md` gehört hier aber nicht rein, oder? kannst du das bitte hier rauslösen und einen neuen pull-request dafür aufmachen?

Ist jetzt in #34

2022-07-21 06:47 UTC, bcg7 commented
sieht erst einmal gut aus.

2022-07-21 07:07 UTC, bcg7 submitted a review, later dismissed

2022-07-27 15:58 UTC, cagix approved these changes

2022-07-27 15:58 UTC, merged