WIP: rem/add Kommentare Vl 3
Compilerbau/CB-Lecture-Bachelor pull request #8
Opened 2022-06-08 15:31 UTC by liketechnik

# Todo (für @liketechnik)

1. Konsistenz der verbleibenden Inhalte prüfen

2022-06-08 20:04 UTC, bcg7 commented
Das muss Carsten entscheiden.

2022-06-09 07:10 UTC, cagix requested changes
Bitte die Datei flex.md direkt im Branch/PR löschen. Sonst bleibt nach dem Skript ne leere Datei zurück.

2022-07-20 09:57 UTC, cagix approved these changes
lgtm

2022-07-27 15:48 UTC, cagix approved these changes

2022-07-27 15:49 UTC, merged